[package]
name = "smartcalc-tui"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
colored = "2.0.0"
linefeed = "0.6.0"
