name: Watch upstream for new releases

on:
  workflow_dispatch:
  schedule:
    # daily at 9am PDT
    - cron: '0 16 * * *'

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: install tomlq
        run: pip install yq
      - uses: actions/checkout@v3
      - name: check smartcalc-tui dependency version
        id: tui
        run: echo "::set-output name=version::$(tomlq -r '.dependencies.smartcalc' Cargo.toml)"
      - uses: actions/checkout@v3
        with:
          repository: erhanbaris/smartcalc
          path: smartcalc
      - name: check upstream smartcalc version
        id: lib
        run: echo "::set-output name=version::$(tomlq -r '.package.version' smartcalc/Cargo.toml)"
      - if: ${{ steps.tui.outputs.version != steps.lib.outputs.version }}
        name: update dependency version
        run: |
          rm -rf smartcalc
          sed -i 's/version = "${{ steps.tui.outputs.version }}"/version = "${{ steps.lib.outputs.version }}"/' Cargo.toml
          sed -i 's/smartcalc = "${{ steps.tui.outputs.version }}"/smartcalc = "${{ steps.lib.outputs.version }}"/' Cargo.toml
      - if: ${{ steps.tui.outputs.version != steps.lib.outputs.version }}
        name: create PR to update dependency
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: update smartcalc to ${{ steps.lib.outputs.version }}
          branch: chore/smartcalc-${{ steps.lib.outputs.version }}
          title: Update smartcalc to ${{ steps.lib.outputs.version }}
          body: >-
            This is an auto-generated PR created because `smartcalc` appears
            to have recently released a new version. The dependency version
            has been incremented automatically - please make any additional
            changes required (if any) and merge/release on crates.io
            :slightly_smiling_face:
